Packages:
  nipype:
    interfaces:
      fsl:
        AR1Image: process_enabled
        AccuracyTester: process_enabled
        ApplyMask: process_enabled
        ApplyTOPUP: process_enabled
        ApplyWarp: process_enabled
        ApplyXFM: process_enabled
        AvScale: process_enabled
        B0Calc: process_enabled
        BEDPOSTX: process_enabled
        BEDPOSTX5: process_enabled
        BET: process_enabled
        BinaryMaths: process_enabled
        ChangeDataType: process_enabled
        Classifier: process_enabled
        Cleaner: process_enabled
        Cluster: process_enabled
        Complex: process_enabled
        ContrastMgr: process_enabled
        ConvertWarp: process_enabled
        ConvertXFM: process_enabled
        CopyGeom: process_enabled
        DTIFit: process_enabled
        DilateImage: process_enabled
        DistanceMap: process_enabled
        EPIDeWarp: process_enabled
        Eddy: process_enabled
        EddyCorrect: process_enabled
        EpiReg: process_enabled
        ErodeImage: process_enabled
        ExtractROI: process_enabled
        FAST: process_enabled
        FEAT: process_enabled
        FEATModel: process_enabled
        FEATRegister: process_enabled
        FILMGLS: process_enabled
        FIRST: process_enabled
        FLAMEO: process_enabled
        FLIRT: process_enabled
        FNIRT: process_enabled
        FSLCommand: process_enabled
        FUGUE: process_enabled
        FeatureExtractor: process_enabled
        FilterRegressor: process_enabled
        FindTheBiggest: process_enabled
        GLM: process_enabled
        ICA_AROMA: process_enabled
        ImageMaths: process_enabled
        ImageMeants: process_enabled
        ImageStats: process_enabled
        Info: process_enabled
        InvWarp: process_enabled
        IsotropicSmooth: process_enabled
        L2Model: process_enabled
        Level1Design: process_enabled
        MCFLIRT: process_enabled
        MELODIC: process_enabled
        MakeDyadicVectors: process_enabled
        MaxnImage: process_enabled
        MeanImage: process_enabled
        MedianImage: process_enabled
        Merge: process_enabled
        MinImage: process_enabled
        MotionOutliers: process_enabled
        MultiImageMaths: process_enabled
        MultipleRegressDesign: process_enabled
        Overlay: process_enabled
        PRELUDE: process_enabled
        PercentileImage: process_enabled
        PlotMotionParams: process_enabled
        PlotTimeSeries: process_enabled
        PowerSpectrum: process_enabled
        PrepareFieldmap: process_enabled
        ProbTrackX: process_enabled
        ProbTrackX2: process_enabled
        ProjThresh: process_enabled
        Randomise: process_enabled
        Reorient2Std: process_enabled
        RobustFOV: process_enabled
        SMM: process_enabled
        SUSAN: process_enabled
        SigLoss: process_enabled
        SliceTimer: process_enabled
        Slicer: process_enabled
        Smooth: process_enabled
        SmoothEstimate: process_enabled
        SpatialFilter: process_enabled
        Split: process_enabled
        SwapDimensions: process_enabled
        TOPUP: process_enabled
        TemporalFilter: process_enabled
        Threshold: process_enabled
        TractSkeleton: process_enabled
        Training: process_enabled
        TrainingSetCreator: process_enabled
        UnaryMaths: process_enabled
        VecReg: process_enabled
        WarpPoints: process_enabled
        WarpPointsFromStd: process_enabled
        WarpPointsToStd: process_enabled
        WarpUtils: process_enabled
        XFibres: process_enabled
        XFibres5: process_enabled
      spm:
        Analyze2nii: process_enabled
        ApplyInverseDeformation: process_enabled
        ApplyTransform: process_enabled
        CalcCoregAffine: process_enabled
        Coregister: process_enabled
        CreateWarped: process_enabled
        DARTEL: process_enabled
        DARTELNorm2MNI: process_enabled
        DicomImport: process_enabled
        EstimateContrast: process_enabled
        EstimateModel: process_enabled
        FieldMap: process_enabled
        Info: process_disabled
        Level1Design: process_enabled
        MultipleRegressionDesign: process_enabled
        NewSegment: process_enabled
        Normalize: process_enabled
        Normalize12: process_enabled
        OneSampleTTestDesign: process_enabled
        PairedTTestDesign: process_enabled
        Realign: process_enabled
        Reslice: process_enabled
        ResliceToReference: process_enabled
        SPMCommand: process_enabled
        Segment: process_enabled
        SliceTiming: process_enabled
        Smooth: process_enabled
        Threshold: process_enabled
        TwoSampleTTestDesign: process_enabled
        VBMSegment: process_enabled
